//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// w01draw.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_TOOLBAR_DEBUG               126
#define IDR_MAINFRAME                   128
#define IDR_w01drawTYPE                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FONTVIEW                132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_FONTXMLVIEW             134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDI_DOCINF_VIEW                 169
#define IDB_EXPLORER_24                 170
#define IDI_FONT_VIEW                   170
#define IDR_SORT                        171
#define IDI_FONT_VIEW1                  171
#define IDI_FONTXML_VIEW                171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_TEXTVIEW                185
#define ID_VIEW_DOCINFVIEW              186
#define ID_VIEW_PAGEINFVIEW             187
#define ID_VIEW_NUMERICALVIEW           188
#define ID_INDICATOR_POSTEXT            189
#define ID_INDICATOR_PAPER              190
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDC_ZOOMIN                      310
#define IDC_ZOOMOUT                     311
#define IDC_HANDOVER                    312
#define IDC_HANDDRAG                    313
#define IDD_INFODIALOG                  316
#define IDR_POPUP_TAB                   317
#define IDR_DEBUG                       318
#define IDR_w01drawTYPE1                318
#define IDR_w01drawDEBUG                318
#define IDR_FONTXML                     321
#define IDD_SELFONTDIALOG               323
#define IDR_DOCFONT                     325
#define IDR_PAGEINFO                    326
#define IDD_GOTODIALOG                  327
#define IDR_NUMERICAL                   328
#define IDD_SAVEIMGDIALOG               330
#define IDC_POS_FRAME                   1000
#define IDC_MFCFONTCOMBO1               1001
#define IDC_FONTCOMBO                   1005
#define IDC_TXT_FONTNAME                1006
#define IDC_CHK_DEVICE                  1007
#define IDC_CHK_RASTER                  1008
#define IDC_CHK_TRUETYPE                1009
#define IDC_COM_PAGES                   1009
#define IDC_COMBO1                      1011
#define IDC_TEXT_OUT                    1012
#define IDC_BROWSE                      1013
#define IDC_SAVEALL                     1014
#define IDS_DOC_INFO                    2000
#define IDS_FONT_INFO                   2001
#define IDS_USER_INFO                   2002
#define IDS_TEXT_INFO                   2003
#define IDS_XMLF_INFO                   2004
#define IDS_XMLF_FILTER                 2005
#define IDS_DOCINF_INFO                 2006
#define IDS_HEADER_INFO                 2007
#define IDS_PAGE_INFO                   2008
#define IDS_PAGE_NO                     2009
#define IDS_PAGE_WIDTH                  2010
#define IDS_PAGE_HEIGHT                 2011
#define IDS_PAGE_ROTATE                 2012
#define IDS_PAGE_TEXTCNT                2013
#define IDS_PAGE_LINECNT                2014
#define IDS_PAGE_IMAGENT                2015
#define IDS_PAGE_OVLYCNT                2016
#define IDS_OBJECT_NO                   2017
#define IDS_OBJECT_TYPE                 2018
#define IDS_OBJECT_X                    2019
#define IDS_OBJECT_Y                    2020
#define IDS_OBJECT_WIDTH                2021
#define IDS_OBJECT_HEIGHT               2022
#define IDS_OBJECT_SIZE                 2023
#define IDS_OBJECT_SCALEX               2024
#define IDS_OBJECT_SCALEY               2025
#define IDS_NUMERICAL_INFO              2026
#define IDS_ZOOM_10                     2100
#define IDS_ZOOM_25                     2101
#define IDS_ZOOM_50                     2102
#define IDS_ZOOM_75                     2103
#define IDS_ZOOM_100                    2104
#define IDS_ZOOM_125                    2105
#define IDS_ZOOM_150                    2106
#define IDS_ZOOM_200                    2107
#define IDS_ZOOM_400                    2108
#define IDS_ZOOM_800                    2109
#define IDS_ZOOM_1600                   2110
#define IDS_ZOOM_2400                   2111
#define IDS_ZOOM_3200                   2112
#define IDS_ZOOM_6400                   2113
#define IDS_OVLY_INFO                   2114
#define IDS_OBJECT_CNT                  2115
#define IDS_TXT_VERSION                 2149
#define IDS_TXT_SHEET                   2150
#define IDS_TXT_FNAME                   2151
#define IDS_TXT_TITLE                   2152
#define IDS_TXT_FONT                    2153
#define IDS_TXT_FONTNAME                2154
#define IDS_TXT_BASE                    2155
#define IDS_TXT_CREATEDATE              2156
#define IDS_TXT_UPDATEDATE              2157
#define IDS_TXT_RECORDLEN               2158
#define IDS_TXT_TOTALPAGE               2159
#define IDS_TXT_RECORD                  2160
#define IDS_TXT_NO_REC                  2161
#define IDS_TXT_NO_USERINFO             2162
#define IDS_TXT_NO_OVLY                 2163
#define IDS_TXT_NO_PAGE                 2164
#define IDS_TXT_NO_IMAGE                2165
#define IDS_TXT_NO_TEXTTBL              2166
#define IDS_TXT_NO_TEXTPOS              2167
#define IDS_TXT_NO_COMMENT              2168
#define IDS_TXT_NO_STAMP                2169
#define IDS_TXT_NO_TAG                  2170
#define IDS_TXT_NO_MARKER               2171
#define IDS_TXT_NO_FONT                 2172
#define IDS_TXT_NO_BINARY               2173
#define IDS_COLNAME_TEXT                2180
#define IDS_COLNAME_TEXTPOS             2181
#define IDS_COLNUME_TEXTATTR            2182
#define IDS_COLNUME_TEXTFONT            2183
#define IDS_COLNAME_CELL                2184
#define IDS_COLNAME_DISPFONT            2185
#define IDS_MSG_TIPS                    2186
#define IDS_XML_COMMON                  2187
#define IDS_CELL_FILTER                 2188
#define IDS_MSG_NOMEMORY                2189
#define IDS_DIR_IMAGE                   2190
#define IDS_FILE_SAVED                  2191
#define IDS_WSI_FILTER                  2192
#define IDS_MSG_OPNEWSI                 2193
#define ID_LIST_EXPAND                  32700
#define ID_VIEW_FILECTRL                32701
#define ID_VIEW_ZOOMIN                  32702
#define ID_VIEW_ZOOMOUT                 32703
#define ID_VIEW_SHOWWIDE                32704
#define ID_VIEW_FULL                    32705
#define ID_VIEW_ZOOMCOMBO               32706
#define ID_VIEW_SHOWINFO                32707
#define ID_VIEW_FIND                    32708
#define ID_VIEW_ESCAPE                  32709
#define ID_VIEW_TEXT                    32710
#define ID_VIEW_OVLY                    32711
#define ID_VIEW_IMAGE                   32712
#define ID_VIEW_LINE                    32713
#define ID_VIEW_TEXTXY                  32714
#define ID_VIEW_CELLDEF                 32715
#define ID_VIEW_HIGHLIGHT               32716
#define ID_VIEW_TIPS                    32717
#define ID_VIEW_DEBUG                   32718
#define ID_VIEW_TEXTDUMP                32719
#define ID_VIEW_IMGOUTPUT               32720
#define ID_VIEW_FONTXML                 32721
#define ID_VIEW_WSI                     32722
#define ID_PAGE_FIRST                   32793
#define ID_PAGE_PREV                    32794
#define ID_PAGE_COUNT                   32795
#define ID_PAGE_NEXT                    32796
#define ID_PAGE_LAST                    32797
#define ID_TEXT_OVLTEXTCOLOR            32806
#define ID_COMBO_OVLTXTCOLOR            32807
#define ID_REFRESH                      32808
#define ID_HIGHLIGHT                    32809
#define ID_SELECTLINE                   32810
#define ID_XML_RELOAD                   32811
#define ID_XML_OPEN                     32812
#define ID_XML_SAVE                     32813
#define ID_XML_DELETE                   32814
#define ID_XML_EXPAND                   32815
#define ID_XML_COLLAPSE                 32816
#define ID_DOCFONT_SYNCTO               32817
#define ID_DOCFONT_SYNCFROM             32818
#define ID_DOCFONT_REFRESH              32819
#define ID_XML_DRAWFONT                 32820
#define ID_PAGEINF_RELOAD               32821
#define ID_NUMS_RELOAD                  32822
#define ID_COLOR_AUTO                   32823
#define ID_COLOR_RED                    32824
#define ID_COLOR_GREEN                  32825
#define ID_COLOR_BLUE                   32826
#define ID_COLOR_DARKRED                32827
#define ID_COLOR_DARKGREEN              32828
#define ID_COLOR_DARKBLUE               32829
#define ID_COLOR_MAGENTA                32830
#define ID_COLOR_DARKYELLOW             32831
#define ID_COLOR_CYAN                   32832
#define IDS_ERR_FILESAVE                32833
#define IDS_DIR_OUTPUT                  32834
#define IDS_MSG_OUTPUTPDF               32835
#define IDS_ERRMSG_OUTPUTPDF            32836
#define IDS_MSG_FILEEXIST               32837
#define ID_FILE_CLOSEALL                32838
#define ID_FILE_CLOSEOTHER              32839
#define ID_FILE_PDF                     32840
#define ID_FILE_OPENCELL                32841
#define ID_FILE_WSI                     32842

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
